export const PRESET_COLORS = [
  { label: "Red", value: "#EF4444" },
  { label: "Dark Red", value: "#B91C1C" },
  { label: "Orange", value: "#F97316" },
  { label: "Dark Orange", value: "#C2410C" },
  { label: "Amber", value: "#F59E0B" },
  { label: "Dark Amber", value: "#B45309" },
  { label: "Yellow", value: "#EAB308" },
  { label: "Lime", value: "#84CC16" },
  { label: "Green", value: "#22C55E" },
  { label: "Dark Green", value: "#15803D" },
  { label: "Emerald", value: "#10B981" },
  { label: "Teal", value: "#14B8A6" },
  { label: "Dark Teal", value: "#0F766E" },
  { label: "Cyan", value: "#06B6D4" },
  { label: "Dark Cyan", value: "#0E7490" },
  { label: "Sky", value: "#0EA5E9" },
  { label: "Blue", value: "#3B82F6" },
  { label: "Dark Blue", value: "#1D4ED8" },
  { label: "Indigo", value: "#6366F1" },
  { label: "Dark Indigo", value: "#4338CA" },
  { label: "Violet", value: "#8B5CF6" },
  { label: "Dark Violet", value: "#6D28D9" },
  { label: "Purple", value: "#A855F7" },
  { label: "Dark Purple", value: "#7E22CE" },
  { label: "Fuchsia", value: "#D946EF" },
  { label: "Dark Fuchsia", value: "#A21CAF" },
  { label: "Pink", value: "#EC4899" },
  { label: "Dark Pink", value: "#BE185D" },
  { label: "Rose", value: "#F43F5E" },
  { label: "Stone", value: "#78716C" },
  { label: "Dark Stone", value: "#57534E" },
  { label: "Slate", value: "#64748B" },
  { label: "Dark Slate", value: "#475569" },
  { label: "Zinc", value: "#71717A" },
  { label: "Brown", value: "#92400E" },
] as const;

export const ICON_OPTIONS = [
  "utensils",
  "coffee",
  "wine",
  "beer",
  "pizza",
  "cake",
  "ice-cream-cone",
  "cup-soda",
  "sandwich",
  "cooking-pot",
  "landmark",
  "church",
  "castle",
  "building",
  "building-2",
  "home",
  "warehouse",
  "school",
  "hospital",
  "hotel",
  "trees",
  "tree-palm",
  "flower-2",
  "mountain",
  "sun",
  "umbrella",
  "waves",
  "tent",
  "fence",
  "shrub",
  "shopping-bag",
  "shopping-cart",
  "store",
  "gift",
  "shirt",
  "gem",
  "watch",
  "scissors",
  "music",
  "headphones",
  "mic",
  "guitar",
  "drum",
  "theater",
  "ticket",
  "film",
  "camera",
  "palette",
  "brush",
  "book-open",
  "library",
  "graduation-cap",
  "globe",
  "map",
  "map-pin",
  "compass",
  "plane",
  "train-front",
  "bus",
  "car",
  "bike",
  "ship",
  "anchor",
  "dumbbell",
  "trophy",
  "medal",
  "heart",
  "star",
  "sparkles",
  "flame",
  "zap",
  "eye",
  "dog",
  "cat",
  "fish",
  "bird",
  "paw-print",
] as const;

export const SOURCE_OPTIONS = [
  { label: "Manual", value: "manual" },
  { label: "CSV Import", value: "csv_import" },
  { label: "Quick Add", value: "quick_add" },
] as const;

export const VISITED_OPTIONS = [
  { label: "All", value: "all" },
  { label: "Visited", value: "true" },
  { label: "Not Visited", value: "false" },
] as const;
